const jobs = [
  {
    id: 1,
    company: "TechNova Solutions",
    title: "Junior Software Developer",
    location: "Pune",
    type: "Full Time",
    salary: "₹4 - 7 LPA",
    experience: "0-2 Years",
    skills: ["JavaScript", "React", "Node.js"],
    logo: "TN",
  },
  {
    id: 2,
    company: "DataSphere Analytics",
    title: "Data Analyst",
    location: "Mumbai",
    type: "Full Time",
    salary: "₹5 - 8 LPA",
    experience: "1-3 Years",
    skills: ["Python", "SQL", "Excel"],
    logo: "DS",
  },
  {
    id: 3,
    company: "CloudPeak Technologies",
    title: "Cloud Support Engineer",
    location: "Bangalore",
    type: "Full Time",
    salary: "₹5 - 9 LPA",
    experience: "0-2 Years",
    skills: ["AWS", "Linux", "Docker"],
    logo: "CP",
  },
  {
    id: 4,
    company: "PixelCraft Studio",
    title: "UI/UX Designer",
    location: "Remote",
    type: "Remote",
    salary: "₹4 - 7 LPA",
    experience: "1-3 Years",
    skills: ["Figma", "UI Design", "UX Research"],
    logo: "PC",
  },
  {
    id: 5,
    company: "AppVertex Labs",
    title: "React Developer",
    location: "Hyderabad",
    type: "Full Time",
    salary: "₹6 - 10 LPA",
    experience: "1-3 Years",
    skills: ["React", "JavaScript", "REST API"],
    logo: "AV",
  },
  {
    id: 6,
    company: "MarketBridge",
    title: "Digital Marketing Intern",
    location: "Pune",
    type: "Internship",
    salary: "₹12K - 18K / Month",
    experience: "Fresher",
    skills: ["SEO", "Social Media", "Google Ads"],
    logo: "MB",
  },
];

export default jobs;